// <auto-generated />
using System;
using MVCPractice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCPractice.Migrations
{
    [DbContext(typeof(RecipeManagementContext))]
    [Migration("20230725142535_IngredientAdd")]
    partial class IngredientAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCPractice.Models.AuthorModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Fearlessly dedicated to making healthy food that's affordable, easy-to-make, and best of all DELISH.",
                            Email = "hello@wellplated.com",
                            Name = "Erin Clarke"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Develops recipes professionally, as well as having an extensive cooking history; from attending school to becoming an executive chef.",
                            Email = "Tschul@heygrillhey.com",
                            Name = "Taylor Shulman"
                        });
                });

            modelBuilder.Entity("MVCPractice.Models.IngredientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "English Muffin",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pepperoni",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cheese",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Banana Pepper",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pizza Sauce",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Olive Oil",
                            RecipeId = 1
                        });
                });

            modelBuilder.Entity("MVCPractice.Models.RecipeModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CookTime = 15,
                            Description = "Easy english muffin pizzas that are quick and simple to make. Perfect for a quick lunch.",
                            Name = "English Muffin Pizza"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CookTime = 900,
                            Description = "Iconic Texas Style brisket. Now yours in only 15 hours!",
                            Name = "Texas Style Smoked Beef Brisket"
                        });
                });

            modelBuilder.Entity("MVCPractice.Models.IngredientModel", b =>
                {
                    b.HasOne("MVCPractice.Models.RecipeModel", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MVCPractice.Models.RecipeModel", b =>
                {
                    b.HasOne("MVCPractice.Models.AuthorModel", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
