// <auto-generated />
using System;
using MVCPractice.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCPractice.Migrations
{
    [DbContext(typeof(RecipeManagementContext))]
    [Migration("20230724184919_AddAuthors")]
    partial class AddAuthors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCPractice.Models.AuthorModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Fearlessly dedicated to making healthy food that's affordable, easy-to-make, and best of all DELISH.",
                            Email = "hello@wellplated.com",
                            Name = "Erin Clarke"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Develops recipes professionally, as well as having an extensive cooking history; from attending school to becoming an executive chef.",
                            Email = "",
                            Name = "Taylor Shulman"
                        });
                });

            modelBuilder.Entity("MVCPractice.Models.RecipeModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookTime = 15,
                            Description = "Easy english muffin pizzas that are quick and simple to make. Perfect for a quick lunch.",
                            Name = "English Muffin Pizza"
                        },
                        new
                        {
                            Id = 2,
                            CookTime = 900,
                            Description = "Iconic Texas Style brisket. Now yours in only 15 hours!",
                            Name = "Texas Style Smoked Beef Brisket"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
